version: "3.6"

services:
  mongo:
    image: mongo:6.0.8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    volumes:
      - etcd_data:/bitnami/etcd

  indexer_custom_resolutions:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8001:8001"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/custom_resolutions.ts
      - --status-server-address=0.0.0.0:8001
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: custom-resolutions
      AUTH_TOKEN: dna_xxx

  indexer_id_owners:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8002:8002"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/id_owners.ts
      - --status-server-address=0.0.0.0:8002
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: id-owners
      AUTH_TOKEN: dna_xxx

  indexer_id_user_data:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8003:8003"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/id_user_data.ts
      - --status-server-address=0.0.0.0:8003
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: id-user-data
      AUTH_TOKEN: dna_xxx

  indexer_id_verifier_data:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8004:8004"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/id_verifier_data.ts
      - --status-server-address=0.0.0.0:8004
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: id-verifier-data
      AUTH_TOKEN: dna_xxx

  indexer_old_domains:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8005:8005"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/old-domains.ts
      - --status-server-address=0.0.0.0:8005
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: old-domains
      AUTH_TOKEN: dna_xxx

  indexer_referral_revenues:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8006:8006"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/referral_revenues.ts
      - --status-server-address=0.0.0.0:8006
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: referral-revenues
      AUTH_TOKEN: dna_xxx

  indexer_auto_renew_approvals:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8007:8007"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/auto_renew_approvals.ts
      - --status-server-address=0.0.0.0:8007
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: auto-renew-approvals
      AUTH_TOKEN: dna_xxx

  indexer_auto_renew_flows:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8008:8008"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/auto_renew_flows.ts
      - --status-server-address=0.0.0.0:8008
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: auto-renew-flows
      AUTH_TOKEN: dna_xxx

  indexer_renewals:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8009:8009"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/renewals.ts
      - --status-server-address=0.0.0.0:8009
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: renewals
      AUTH_TOKEN: dna_xxx

  indexer_sales:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8010:8010"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/sales.ts
      - --status-server-address=0.0.0.0:8010
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: sales
      AUTH_TOKEN: dna_xxx

  boost_claims:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8010:8010"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/boost_claims.ts
      - --status-server-address=0.0.0.0:8010
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: boost_claims
      AUTH_TOKEN: dna_xxx


  claimed_achievements:
    image: quay.io/apibara/sink-mongo:0.4.7
    depends_on:
      - etcd
    restart: always
    ports:
      - "8012:8012"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/claimed_achievements.ts
      - --status-server-address=0.0.0.0:8012
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: boost_claims
      AUTH_TOKEN: dna_xxx

volumes:
  etcd_data:
  mongo_data:
